[package]
name = "ownership"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
spectral = "0.6.0"
trybuild = "1.0.85"
