[package]
name = "traits"
version = "0.0.0"
edition = "2021"

[lib]
name = "traits_lib"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
spectral = "0.6.0"
